name: Build & Test
on:
  push:
    branches:
      - interpolation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: Build & Test App
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Get commit count
        id: commit_count
        run: echo "count=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

      - name: Get version info
        id: version_info
        run: |
          VERSION_NAME=$(grep "versionName = " app/build.gradle.kts | head -1 | sed 's/.*"\(.*\)".*/\1/')
          echo "name=${VERSION_NAME}" >> $GITHUB_OUTPUT

      - name: Dependency Review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4.8.2

      - name: Set up JDK
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Check code format
        run: ./gradlew spotlessCheck

      - name: Build app
        run: ./gradlew assembleRelease -Penable-updater

      - name: Sign APK
        uses: r0adkll/sign-android-release@f30bdd30588842ac76044ecdbd4b6d0e3e813478
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: '35.0.1'

      - name: Run unit tests
        id: unit_tests
        run: ./gradlew testReleaseUnitTest

      - name: Upload test report
        if: steps.unit_tests.outcome == 'failure'
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: test-report-${{ github.sha }}
          path: app/build/reports/tests/testReleaseUnitTest

      - name: Upload APK
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: arm64-v8a-${{ github.sha }}
          path: app/build/outputs/apk/release/app-arm64-v8a-release-unsigned-signed.apk

      - name: Upload mapping
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: mapping-${{ github.sha }}
          path: app/build/outputs/mapping/release

      - name: Create Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          tag_name: v${{ steps.version_info.outputs.name }}.${{ steps.commit_count.outputs.count }}
          name: Release v${{ steps.version_info.outputs.name }}.${{ steps.commit_count.outputs.count }}
          target_commitish: ${{ github.sha }}
          draft: false
          prerelease: false
          files: |
            app/build/outputs/apk/release/app-arm64-v8a-release-unsigned-signed.apk
            app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned-signed.apk
            app/build/outputs/apk/release/app-x86-release-unsigned-signed.apk
            app/build/outputs/apk/release/app-x86_64-release-unsigned-signed.apk
            app/build/outputs/apk/release/app-universal-release-unsigned-signed.apk
